[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydantic-ai-api-tool-mapper"
version = "0.1.0"
description = "Library to map APIs and generate Pydantic AI Agent Tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28",
    "packaging>=24.0",
    "pydantic>=2.0",
    "pydantic-ai>=0.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["api_tool_mapper"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "--import-mode=importlib",
    "--cov=api_tool_mapper",
    "--cov-report=term-missing",
]
testpaths = [
    "tests",
]
pythonpath = ["."]
python_files = ["test_*.py", "*_test.py"]
